####################################################################################
#
# Generated by eda_pt_script.tcl	#1
#              eda_pt_conversion.tcl	#1
#              in d:/altera/91sp2/quartus/common/tcl/internal/eda_pt/.
#
# Quartus:  Version 9.1 Build 350 03/24/2010 Service Pack 2 SJ Web Edition
#
# Project:  Microwave
# Revision: Microwave
#
# Date: Tue Dec 25 14:09:19 CST 2018
#
####################################################################################


set _col3 [ get_ports {CP_High}]



set _col16 [ get_pins {inst|inst2|Q0.q}]



set _col17 [ get_pins {inst5|inst13|inst5.q}]



set _col4 [ get_ports {CP_Low}]



set _col18 [ get_pins {inst3|inst1|sub|9.q}]



